### ISSUE TITLE
なんか芋づる式にエラーが出てる

### ISSUE THREAD

**Issue by yanack1225** [yanack1225/PastQuestion#13]
試したこと http://gawawa124.hatenablog.com/entry/2015/03/29/105322
あとは色々やったけど imfoplistがない
<img width="740" alt="2016-11-23 20 15 11" src="https://cloud.githubusercontent.com/assets/16880859/20559807/a68dacda-b1b9-11e6-81c4-89b6a133e16a.png">

**Comment by ShinokiRyosei** [comment]
@yanack1225 `pod update`かけたらどうなる？

**Comment by yanack1225** [comment]
@ShinokiRyosei やってみる。あと、エラー吐いてからコミットしてなかったからコミットした

**Comment by ShinokiRyosei** [comment]
OK

**Comment by yanack1225** [comment]
あー。なんかさっき新しく入れたpodの名前が違ったっぽい。けど関係してる？

**Comment by ShinokiRyosei** [comment]
さっき新しく入れたpodってなに？
また日本語の説明が不十分

**Comment by yanack1225** [comment]
PNChartSwift を入れようとしたらGitのリンク書いてなかったからかうまく入らなかった

**Comment by ShinokiRyosei** [comment]
解決したなら、issueをcloseしといて

**Comment by yanack1225** [comment]
了解。

**Comment by ShinokiRyosei** [comment]
とりあえず自分で解決して、Good job!
