### ISSUE TITLE
Highlight型からのデータの取り出し方がわからない

### ISSUE THREAD

**Issue by yanack1225** [yanack1225/PastQuestion#15]
@ShinokiRyosei highlightからx座標を取り出そうとしているんだけど、これって辞書型じゃないの？
（issue名書き間違えましたごめんなさい）
https://github.com/yanack1225/PastQuestion/blob/NewFunction/PastQToRelease/SchoolMenuViewController.swift#L469

**Comment by ShinokiRyosei** [comment]
@yanack1225 
まず、highlightがどういう型であっても、
```
let dic = "[\(highlight)]"
```
としてる時点で、`dic`は`[String]`になってるのわかる？
```
let dic = [""]
```
ダブルコーテーションってString型になるから、Stringの配列になってるよね？

**Comment by ShinokiRyosei** [comment]
次に、
```
open class Highlight: NSObject
```
っていうふうに定義されてるよね？
`Highlight`型の`highlight`は辞書型じゃないよね？`NSObject`を継承してるよね？

**Comment by ShinokiRyosei** [comment]
Issueのタイトルはタイトルの右側にある`Edit`で編集できるから、次からは間違えてもあとから編集しとこう

**Comment by ShinokiRyosei** [comment]
それからここ
https://github.com/yanack1225/PastQuestion/blob/NewFunction/PastQToRelease/SchoolMenuViewController.swift#L471
`UIAlertController`使おう

**Comment by yanack1225** [comment]
了解！ありがとう！家帰ったら直してコミットします！
