### ISSUE TITLE
ディレクトリ整理

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#16]
今Xcodeから見れるディレクトリ構造が一環した法則に従っていないので、揃える
その後Xcodeプロジェクトを開いたときに出るディレクトリとFinderから見れる本来のディレクトリが一致してないので、そこを一致させる

**Comment by ShinokiRyosei** [comment]
`synx`使ってディレクトリ整理をする
[Xcodeのファイルを整理する Synx](http://qiita.com/Yuta/items/fdce62fcb871912629ce)

**Comment by yanack1225** [comment]
synx を`cocoapods`入れるの？

**Comment by ShinokiRyosei** [comment]
これはスクールでやろう

**Comment by ShinokiRyosei** [comment]
多分自分でやると失敗するかもしれんから

**Comment by yanack1225** [comment]
絶対しそう（笑）了解！

**Comment by ShinokiRyosei** [comment]
@yanack1225 `synx`掛ける前にXcodeのディレクトリ構造見直しといて、Xcodeプロジェクトのディレクトリ構造がそのままFinderに反映されるから

**Comment by yanack1225** [comment]
@ShinokiRyosei  わかった！
