### ISSUE TITLE
セグコンについて

### ISSUE THREAD

**Issue by yanack1225** [yanack1225/PastQuestion#17]
@ShinokiRyosei セグコンの切り替えを今まで isHidden使ってたけどViewを切り替える方法っていうのは違うViewControllerにViewを２つ作るって意味？よくわかんないんだけど。
https://github.com/yanack1225/PastQuestion/blob/NewFunction/PastQToRelease/SchoolMenuViewController.swift#L308
P.S.
明日から冬休みなので冬休み中にちょくちょくissueは消化していきます。

**Comment by ShinokiRyosei** [comment]
@yanack1225 
`UISegmentedControl`の切り替えでなにをしたいのかコードではわからないけど、`UISegmentedControl`のどういう画面をつくりたいのかXDでも手書きでもいいからもらえる？

ちなみに、`TableView`をどのみち使うならなかのデータ切り替えるだけでいいんじゃない？

**Comment by ShinokiRyosei** [comment]
issueどんどん消化していってくれ！
楽しみにしてるよ

**Comment by ShinokiRyosei** [comment]
ViewControllerのUISegmentedControlで画面切り替えたかったら、xib用意してそのxib読み込む形で画面つくればいいと思うよ

**Comment by ShinokiRyosei** [comment]
@yanack1225 
このissueはどうなったの？

**Comment by ShinokiRyosei** [comment]
`README`にあるXDのファイル見ても、`UISegmentedControl`でどういうデータの切り替えをするのか全くわからないんだけど笑

これは全体統計を選ぶとどういう画面になるの？

<img width="377" alt="2016-12-29 19 13 03" src="https://cloud.githubusercontent.com/assets/11238461/21541570/e0b39994-cdfa-11e6-95f0-e5ecd75bd54f.png">

**Comment by yanack1225** [comment]
セグコンを動かすとグラフの値が変わる仕様に変更するつもり。下手に情報を増やすより、視覚的な情報が多いほうが開発も楽だし見栄えいいでしょ？

**Comment by ShinokiRyosei** [comment]
グラフの値だけが変わるだけなら、`xib`を読み込む必要ないんじゃない？
なかのデータが変わってるだけでしょ

**Comment by yanack1225** [comment]
とりあえず、実装してみたからコミットする

**Comment by ShinokiRyosei** [comment]
ブランチはどれ？

**Comment by yanack1225** [comment]
TestConvertにプッシュした。このissue解決したら一旦プルリク送ってまとめておく。やたらとbranchしてごっちゃになってきた。

**Comment by ShinokiRyosei** [comment]
OK
いくつかコードで気になったからコミットにメッセージ残しとくね

**Comment by yanack1225** [comment]
このissue一旦閉じて大丈夫？

**Comment by ShinokiRyosei** [comment]
一旦？
一旦っていうのはどういうこと？

**Comment by yanack1225** [comment]
一旦っていうかセグコンは実装できたからこの件落着かなって

**Comment by ShinokiRyosei** [comment]
そういうことね
なら閉じてOK
