### ISSUE TITLE
Chartsのエラーについて。

### ISSUE THREAD

**Issue by yanack1225** [yanack1225/PastQuestion#19]

**Comment by ShinokiRyosei** [comment]
@yanack1225 
どのターゲットの`Use legacy swift version`を`NO`に設定したの？

**Comment by ShinokiRyosei** [comment]
今エラーメッセージはどの`Build Target`に対して出てるの？
そこが大事じゃない？ちゃんと、エラーが出てるターゲットに対してエラーメッセージの通りに修正してあげよう

**Comment by yanack1225** [comment]
PodFileに出てるよ。それだから修正したつもりなんだけど。

**Comment by ShinokiRyosei** [comment]
Podfileにエラー出てるはずない！
スクショちょうだい

**Comment by ShinokiRyosei** [comment]
一応Podfileのなかも見せて

**Comment by yanack1225** [comment]
Podfileなんも起きてなかった。podのターゲットって言おうとした。ごめん！

**Comment by ShinokiRyosei** [comment]
CocoapodsのターゲットのSwiftのバージョンのエラーってことなら、どうやって直せばいいかわかる？
PastQuestionが`Build Target`なら直せるなら、そこを参考に試行錯誤できる？

**Comment by yanack1225** [comment]
podのBuildTargetを直せばいいの？

**Comment by ShinokiRyosei** [comment]
そうそう

**Comment by yanack1225** [comment]
で、クリキャンの時にそれを直したら大量のエラーが出たんだよねぇ。。。

**Comment by yanack1225** [comment]
で、考えられるのがXcodeのバージョンあげたからかなって思ってQiitaで探したら、こんな記事を見つけてそれもやったんだけど無理だった。
http://qiita.com/ShingoFukuyama/items/e28f2d0bc7adc0db3393

**Comment by ShinokiRyosei** [comment]
これをやれば直るよ

**Comment by yanack1225** [comment]
もう一回試してみる。

**Comment by ShinokiRyosei** [comment]
ナイス！

**Comment by yanack1225** [comment]
結論 **YES** から**NO**にするってQiitaで紹介されてたけど、何故かエラーが999+になるから、直接**NO**にしたら直りました。

**Comment by ShinokiRyosei** [comment]
Good Job!
