### ISSUE TITLE
パスワードを文字が見えないようにしておく

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#26]
パスワードがそのまま見えてしまっているので、そこを直す
![simulator screen shot 2017 01 04 2 42 38](https://cloud.githubusercontent.com/assets/11238461/21617031/879d0f62-d227-11e6-9b41-018a230bffff.png)

**Comment by yanack1225** [comment]
これ、僕が打ってるときにわかりやすくていいなってわざとこうしたんだけど、セキュリティ的にやばい？

**Comment by ShinokiRyosei** [comment]
もちろんヤバい
パスワードそのまま見えるようにしてるアプリ見たことある？

**Comment by yanack1225** [comment]
確かに...ちなみに、パスワードに日本語とか記号が打ち込めないようになってるのもセキュリティ？

**Comment by ShinokiRyosei** [comment]
iOSだとパスワードの文字が見えないようにすると全角とか打ち込めないよ

**Comment by yanack1225** [comment]
あ、そうなんだ。

**Comment by ShinokiRyosei** [comment]
一行で実装できるから早めに実装しちゃいな

**Comment by ShinokiRyosei** [comment]
Nice
