### ISSUE TITLE
ファイル削除

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#3]
PreViewController.swift , SoCYomikomiViewController.swift, ViewController.swift削除

## TODO
- [x] PreViewController.swift
- [x] SoCYomikomiViewController.swift
- [x] ViewController.swift
- [x] AnalogViewController.swift

**Comment by yanack1225** [comment]
消したbranchがあるから閉じます。いらないファイルは適宜消すようにします！

**Comment by ShinokiRyosei** [comment]
いや全部消してから閉じよう

**Comment by ShinokiRyosei** [comment]
消したものをチェックマークつけられるようにしたから、消したらチェックつけていって

**Comment by yanack1225** [comment]
了解！

**Comment by ShinokiRyosei** [comment]
一番上のコメントにチェックマークつけてな

**Comment by yanack1225** [comment]
わかった#22と平行してやってく。

**Comment by ShinokiRyosei** [comment]
@yanack1225 これも5分あれば終わるissueやから、さっさと終わらせてクローズしとき！
