### ISSUE TITLE
UIPickerViewDelegateが効いていない

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#32]
このメソッドもUIPickerViewDelegateのメソッドとマッチしてないよ
https://github.com/yanack1225/PastQuestion/blob/master/PastQToRelease/ToukouViewController.swift#L52

**Comment by yanack1225** [comment]
ごめん！押し間違えた！

**Comment by yanack1225** [comment]
このClassは今使ってないから消したほうがいいね。

**Comment by ShinokiRyosei** [comment]
それならファイルごと消しておいてー

**Comment by yanack1225** [comment]
了解！さっき入試終わったからちょこっとだけやってます！また明後日から卒業試験の勉強しなきゃなんだけどね（笑）

**Comment by ShinokiRyosei** [comment]
OK
