### ISSUE TITLE
UINavigationControllerの警告修正

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#33]
```
self.navigationController?.popViewController(animated: true)
```
となっているのを
```
_ = self.navigationController?.popViewController(animated: true)
```
にして警告を消しておく

**Comment by yanack1225** [comment]
変数を_って置きましょうってたまに怒られるけどどういう意味なの？

**Comment by ShinokiRyosei** [comment]
それは、使わない変数は`_`にすることでメモリーに保存されないようになるから、使わない変数をつくらないでおきましょうっていう警告
使わないならメモリーに保存しないほうがいいよね？

あと、`怒られる`じゃなくて、`警告`ね。そういう言葉もきちんと使おう。`エラー`なのか`警告`なのか、他人に怒られただけなのかってかなり大きい違いやからね。あと今の質問もマークダウンつかって、変数とかの情報をハイライトしておくと相手は見やすいから、そういう気遣いも大事
変数を`_`って置きましょうってたまに怒られるけどどういう意味なの？
