### ISSUE TITLE
IBOutlet宣言の変数がStringってどういうこと？

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#35]
```
@IBOutlet var schollLabel:String!
```
StringをIBOutlet宣言してもなにもできないよ。

https://github.com/yanack1225/PastQuestion/blob/master/PastQToRelease/SchoolMenuViewController.swift#L46

**Comment by yanack1225** [comment]
Labelと間違えて宣言したっぽいけど使ってないから消した！

**Comment by ShinokiRyosei** [comment]
OK
