### ISSUE TITLE
全体統計の意味教えて

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#43]
`SchoolMenuViewController`の全体統計ってどういうロジックで数字出してんのか教えて

**Comment by yanack1225** [comment]
グラフで100点から200点取ってる人がどれぐらい（割合）が見れる様になってるんだけど、全体統計ってので全ユーザーの投稿の割合が見れて、個人成績で自分のスコアに限定したグラフが見れる仕組み

**Comment by ShinokiRyosei** [comment]
OK
理解した
ありがとう
