### ISSUE TITLE
Shinsaという変数の意味教えて

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#44]
`SchoolMenuViewController`の`Shinsa`っていう変数はどういうデータが入ってんの？

**Comment by yanack1225** [comment]
初回起動時に聞かれる質問の答えが数値にして保存してある。

**Comment by ShinokiRyosei** [comment]
だれの回答が入ってるの？
アプリを使っているユーザー自身のデータではないよね？

**Comment by yanack1225** [comment]
得点を投稿した人のマッチングのコード（数字の羅列）の配列だよ。

**Comment by ShinokiRyosei** [comment]
いろんな人のデータとのマッチングはどうやってやるか考えてる？
いろんなユーザーが得点を投稿するよね？
その多数の人の傾向と自身のマッチングはどうやるの？

**Comment by yanack1225** [comment]
その、最初にやった心理テスト的なのでどれぐらいの人が一致するかって内容

**Comment by ShinokiRyosei** [comment]
#48 こっちで議論しよう
