### ISSUE TITLE
String型を分解して配列をつくる

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#47]
```
Shinsa[n][Shinsa[n].index(Shinsa[n].startIndex, offsetBy: i)]
```
これってどういう値を取り出そうとしてるの？
https://github.com/yanack1225/PastQuestion/blob/master/PastQToRelease/SchoolMenuViewController.swift#L484

**Comment by yanack1225** [comment]
shinsaの値の数字がどれくらい一致してるか見るためのコード

**Comment by ShinokiRyosei** [comment]
なるほど
そもそも配列にとして文字列入れてない事自体がよくないけど、ここのコードだけでいうと文字列を分解してないのがわかりにくいコードになってる原因やね

修正しとこう

**Comment by ShinokiRyosei** [comment]
`String`を分解するかどうかはロジック全体が確定してから保存するデータとかを決めてからどうするか決めることやから、今議論することじゃないから、閉じる
