### ISSUE TITLE
マッチングのロジック

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#48]
`YES NO`ボタンそれぞれで、`result`に下のコード書いて実装してるけど、これ配列とかのほうが実装しやすいよね？
```
result = result * 10 + 2
```

たとえばfor文回すときも、決め打ちで`for i in 0 ... 9`という風に書かないと行けないけど、これって質問の項目の数とfor文の回る回数が論理的に一致してないし、コードの量も増えるよね。
https://github.com/yanack1225/PastQuestion/blob/master/PastQToRelease/ShinsaViewController.swift#L58

そのせいで、
```
String(result[result.index(result.startIndex, offsetBy: i)])
```
こういう難しいロジック組む必要が出てしまっているんじゃない？
そもそも配列にしよう。保存するときは、辞書型にしたほうがいいかもしれんけどね。

あと、普通は`YES NO`みたいな二択で数字使うなら、習慣的に`01`を使うと思うよ。
でも、`YES NO`みたいなわかりやすい二択は`Bool`使ったほうが値の中身と回答された中身がわかりやすいよね？

**Comment by yanack1225** [comment]
配列にするように変更しておく`Bool`にしなかったのは、どちらでもないって選択肢が仮で実装されてたから。リリースするまでに消すか実装するか決めたいんだけど。。

**Comment by ShinokiRyosei** [comment]
#47 
をつかって、ローカル側で配列にするのもありだとは思うけど、そもそも配列とか辞書型にできるならそっちのほうがいいと思う

**Comment by yanack1225** [comment]
辞書型にする必要ってあるの？質問の内容も順番も全員同じだし。

**Comment by ShinokiRyosei** [comment]
辞書型のほうがFirebaseに保存するときに、キーとバリューがそれぞれあってわかりやすくない？

**Comment by yanack1225** [comment]
なんで配列にしなかったか思い出したんだけど、 #44 でShinsaでマッチングのデータを配列にさせてるって言ったけど、配列の中に配列入れたらこんがらがりそうでやめたんだ。
https://github.com/yanack1225/PastQuestion/issues/44#issuecomment-270356596

**Comment by yanack1225** [comment]
心テストが一致してた人数/全体の人数 でマッチングを決めるつもりだった

**Comment by ShinokiRyosei** [comment]
心理テストの一致って部分一致はどうする予定？

**Comment by ShinokiRyosei** [comment]
そもそもそこのマッチングって心理テストなのか？
学校決める要素って部活盛んとかサッカー部強いとか、進学校とかでどこを重視するかじゃないの？

**Comment by ShinokiRyosei** [comment]
心理テストでどういう性格の生徒が集まるかで学校を決めるとは思えんねんけど

**Comment by yanack1225** [comment]
一応、心理テストは仮でつけてる。本当は "部活頑張りたいですか？"とか"大学は国立志望ですか？"とかそういう内容にする予定。これも塾の経営者さんに相談する。

**Comment by ShinokiRyosei** [comment]
OK

**Comment by ShinokiRyosei** [comment]
Q2は解決ね

**Comment by ShinokiRyosei** [comment]
Q1については？

**Comment by ShinokiRyosei** [comment]
心テストが一致してた人数/全体の人数 でマッチングを決めるつもりだった
→　
心理テストの一致って部分一致はどういう風に処理するつもり

**Comment by yanack1225** [comment]
あ、了解。

**Comment by yanack1225** [comment]
多分、質問の内容ごとに一致率が見れたほうがいいかなって思ってる。

**Comment by yanack1225** [comment]
最初はグラフの丸いところをタップするとアラートで得点ごとの一致率が見れるような感じに実装仕掛けてたんだけど。

**Comment by ShinokiRyosei** [comment]
なるほど
`心テストが一致してた人数/全体の人数`の心理テストの一致というのは質問ごとに出すの？

**Comment by yanack1225** [comment]
`心テストが一致してた人数/全体の人数*100`にする。

**Comment by ShinokiRyosei** [comment]
グラフの点は心理テストの設問と対応してなくない？
それともグラフの点をタップすると`その得点帯に存在するユーザーの内でどれくらい心理テストがマッチするか`ということ？

**Comment by yanack1225** [comment]
質問ごとに出したいけど、レイアウト的に

**Comment by yanack1225** [comment]
そういうこと

**Comment by yanack1225** [comment]
だけど、それって無駄かなって思った

**Comment by ShinokiRyosei** [comment]
なるほど
`その得点帯に存在するユーザーの内でどれくらい心理テストがマッチするか`っていうのはあんまり意味ないかな

**Comment by yanack1225** [comment]
だよね。

**Comment by ShinokiRyosei** [comment]
自分の回答が、`Y, N, Y, N`だとして、
その他のユーザーが、3人いたら、`Y, Y, Y, Y`, `N, N, N, N`, `N, Y, N, Y`
(YはYESでの回答、NがNOでの回答だとして)
っていうのがいたら、自分のマッチング率は何%になるの？

**Comment by ShinokiRyosei** [comment]
手書きでいいから、計算式も出してもらえる？

**Comment by yanack1225** [comment]
それを今まではマッチング率0%（完全一致数0/3）って考えていたんだけど、それじゃあ一致する可能性が低すぎるから
Q1 適合率33%
Q2 適合率33%
Q3 適合率33%
Q4 適合率33%
って表示させて総合マッチング率33%（平均）にしようかなって

**Comment by yanack1225** [comment]
計算式ってほど複雑でもないけど

**Comment by ShinokiRyosei** [comment]
なるほど
それはどういう計算式で、それぞれの質問のマッチング率が決まってるの？

**Comment by yanack1225** [comment]
そういうこと。

**Comment by ShinokiRyosei** [comment]
計算式教えて

**Comment by yanack1225** [comment]
`Int(心テストが一致してた人数/全体の人数*100)`

**Comment by ShinokiRyosei** [comment]
今の状態で`YESNO`を`01`とかでやるなら、`平均値からどれだけ乖離しているか`でマッチング率出せるんじゃない？

**Comment by ShinokiRyosei** [comment]
タップするごとに`心理テストが一致して人数`を弾き出すの処理重たいんじゃない？

**Comment by yanack1225** [comment]
あ、そっか

**Comment by ShinokiRyosei** [comment]
いや違うわ

**Comment by yanack1225** [comment]
頭ごっちゃになってきた

**Comment by ShinokiRyosei** [comment]
志望校ごとにマッチングださないといけないから、サーバー自分で立ててサーバー内部で自動でやるなら別やけど、平均値をFirebaseに保存とかしとくのは現実的じゃないわ
わすれて今のロジックのままでいい！

**Comment by yanack1225** [comment]
?????

**Comment by yanack1225** [comment]
つまりこのままのメカニズムでいいの？

**Comment by yanack1225** [comment]
でも、今度のアップデートでせっかくRubyさらってきたからそれ用のサーバー作ってみても面白いかなって一瞬思った

**Comment by ShinokiRyosei** [comment]
RailsとFirebaseをあわせるの多分面倒やで

**Comment by yanack1225** [comment]
そうなんだ。DBだけFirebase使えば良いのかと思った。

**Comment by ShinokiRyosei** [comment]
とりあえずタップにごとに計算するんじゃなくて、画面表示し終わったくらいで、計算しといてタップしたらマッチング率を表示するくらいの処理に変えておく必要はあると思う
タップごとにやるのはオススメしない

**Comment by yanack1225** [comment]
とりあえずロジックはこれで解決？

**Comment by ShinokiRyosei** [comment]
解決だね

**Comment by ShinokiRyosei** [comment]
処理の順序だけかな

**Comment by yanack1225** [comment]
そうだね

**Comment by ShinokiRyosei** [comment]
できるなら、railsでサーバー立てて、志望校ごとの平均値出しておくのが本当はいいから、一度試してみるのはいいと思うよ

**Comment by yanack1225** [comment]
もう半年Webサービス履修しないとできなさそう 笑

**Comment by yanack1225** [comment]
まぁ、一旦忘れておく 笑

**Comment by ShinokiRyosei** [comment]
自力で挑戦してみるのすごい勉強になると思うよ

**Comment by yanack1225** [comment]
うん。去年の上半期にWebサービスコースに行ってSwift極力メンターに頼らずに（とかいってTwitterでよくしのきんに質問したけど）リリースできたのはすごい経験だった

**Comment by ShinokiRyosei** [comment]
同じことrailsでもやってみるのを勧めるよ

**Comment by yanack1225** [comment]
うん！今Swiftで手一杯だし一応、入試2週間前だから控えとくけど、2月上旬めっちゃ暇だからその頃にやってみる！

**Comment by ShinokiRyosei** [comment]
OK
期待してる

**Comment by yanack1225** [comment]
あれだね。違うbranchで切っておいて、来年くらいにひょこっとアプデできたらいいかもって思った。
