### ISSUE TITLE
プロジェクトに入っているplayground削除

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#49]
なんでプロジェクトの中に、Playground入ってんの？
必要ある？

**Comment by yanack1225** [comment]
多分、なんかの検証する時に間違えてプロジェクトファイル内で作っちゃった

**Comment by ShinokiRyosei** [comment]
OK
消そう！

**Comment by yanack1225** [comment]
消した！さっきしゅんたからGithubで無料で非公開レポを取得する方法教えてくれたから、今度非公開にしていい？

**Comment by ShinokiRyosei** [comment]
設定からコントリビューターにおれを追加してくれたらプライベートリポジトリでいいよ

**Comment by yanack1225** [comment]
っていうかこのレポジトリをプライベートに変更することってできるよね

**Comment by ShinokiRyosei** [comment]
できるよ
