### ISSUE TITLE
didReceiveMemoryWarning削除

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#5]
必要ないので、削除しましょう。

**Comment by ShinokiRyosei** [comment]
https://github.com/yanack1225/PastQuestion/blob/master/PastQToRelease/KekkaViewController.swift#L23-L26

**Comment by yanack1225** [comment]
そもそも使ってないコードだったからClassごと消したので後でコミットします。

**Comment by ShinokiRyosei** [comment]
これリンク貼った`ViewController`だけじゃなくて、全部の`ViewController`に当てはまるから、全部の`ViewController`から消してからcloseして
説明不足でごめん

**Comment by yanack1225** [comment]
了解！

**Comment by ShinokiRyosei** [comment]
@yanack1225 これも5分あれば終わるやろ？
ちゃっちゃとおわらせちゃいな！

**Comment by yanack1225** [comment]
全部消した！

**Comment by ShinokiRyosei** [comment]
Good job!

**Comment by yanack1225** [comment]
関係ないけど高校受かりました。

**Comment by ShinokiRyosei** [comment]
おお！おめでとう

**Comment by ShinokiRyosei** [comment]
このファイルとか出来てないよ
https://github.com/yanack1225/PastQuestion/blob/TestConvert/PastQToRelease/JikosyoukaiViewController.swift

**Comment by ShinokiRyosei** [comment]
https://github.com/yanack1225/PastQuestion/blob/TestConvert/PastQToRelease/ToukouViewController.swift
