### ISSUE TITLE
コードチェック ブランチTestConvert

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#54]
コードチェックしたから修正しといて
スペルミス一個しかないけどね
https://github.com/yanack1225/PastQuestion/commit/ab29bfd1f506edefbf2f26ae0248b63921d46cf5

**Comment by ShinokiRyosei** [comment]
https://github.com/yanack1225/PastQuestion/commit/0a81f422418a0f68abb9b2d3d2f2f6e134e06850

**Comment by ShinokiRyosei** [comment]
@yanack1225 上記コメントのほうもよろしく

**Comment by ShinokiRyosei** [comment]
https://github.com/yanack1225/PastQuestion/commit/0a81f422418a0f68abb9b2d3d2f2f6e134e06850

**Comment by ShinokiRyosei** [comment]
終わったら、コミットしてプッシュしてこのissueクローズしといて

**Comment by ShinokiRyosei** [comment]
終わったら、 #3 のコメントのチェック欄にチェックマーク入れとくのと、 #6 のissueを再度クローズしておくこと

**Comment by ShinokiRyosei** [comment]
@yanack1225 このissueは取り掛かってる？

**Comment by yanack1225** [comment]
ちょっとコード書くのは入試終わるまでお休みしようかと。一度書きはじめるときりがないから。それと、新しいUI決めたら要らなくなるコードも出てくるかもしれないから。

**Comment by ShinokiRyosei** [comment]
いらなくなるコードと命名おかしいとかの理由から修正しないといけないコードってとりあえず別じゃないかな？
機能を考えて実装するのと、とりあえず名前とか間違ってるから修正を実装するのはわけて考えていいよ。入試後でいいから、修正だけでコミットつくってプッシュしといて

**Comment by yanack1225** [comment]
わかった。
