### ISSUE TITLE
ChartsとPNChartsのライブラリ重複

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#55]
`Charts`と`PNCharts`どっちも`Cocoapods`で入れてるけど、どっちもいるの？

**Comment by yanack1225** [comment]
`Charts`が使えないってなったら使う非常用として入れてた

**Comment by ShinokiRyosei** [comment]
無駄なライブラリ入れるだけビルドの時間長くなるから、そういうのやめとき
使いにくいときに、使えないほう消して新しいライブラリ入れるならわかるけど、非常用とか意味ないから、消しとき

**Comment by yanack1225** [comment]
そうする！ あと、昨日の議論をもとにXD更新しました

**Comment by ShinokiRyosei** [comment]
この画面はどういう画面？
<img width="378" alt="2017-01-06 17 10 06" src="https://cloud.githubusercontent.com/assets/11238461/21711765/05ecb698-d434-11e6-9f66-8564ec1f2431.png">
