### ISSUE TITLE
マージコンフリクト

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#56]
このコミットで`Storyboard`にマージの際のコンフリクトの文字列混じってるよ

https://github.com/yanack1225/PastQuestion/commit/e6a2ea14b580297ca452f6b5a227b1afa35841c4

**Comment by ShinokiRyosei** [comment]
`MySoCViewController.swift`にもコンフリクトの文字列混じってるね

**Comment by yanack1225** [comment]
え。これって戻すしかない？

**Comment by yanack1225** [comment]
とりあえず、作業用branchをコンフリフトの文字が入る直前に戻したんだけど大丈夫？

**Comment by ShinokiRyosei** [comment]
それでいいと思うよ
あとはフォースプッシュでGitHubに上げればいいと思う

**Comment by yanack1225** [comment]
今あげた！

**Comment by ShinokiRyosei** [comment]
OK

**Comment by ShinokiRyosei** [comment]
使わなくなったブランチ削除しときな

**Comment by ShinokiRyosei** [comment]
このissueも出来てないよ
https://github.com/yanack1225/PastQuestion/blob/ReleaseTo2.0/PastQToRelease/Main.storyboard
