### ISSUE TITLE
コードを書き換えるとSetPlaceCellが見つからないとエラーが出る

### ISSUE THREAD

**Issue by yanack1225** [yanack1225/PastQuestion#57]
普通にエラー開いたり、そのままビルドし直したら直るんだけど無視して大丈夫？

**Comment by ShinokiRyosei** [comment]
どう書き換えたの？
コミットのリンクちょうだい

**Comment by yanack1225** [comment]
どうっていうか、インデント直したり、print文消したりするだけでエラーが履かれてビルドしたら直るってのが繰り返されてる。

**Comment by yanack1225** [comment]
なんか出なくなった。
