### ISSUE TITLE
命名おかしい！

### ISSUE THREAD

**Issue by ShinokiRyosei** [yanack1225/PastQuestion#6]
https://github.com/yanack1225/PastQuestion/blob/master/PastQToRelease/TableViewCellType1ViewController.swift

`SetPlaceTableViewCell`とかにしよう

**Comment by yanack1225** [comment]
変更しました！

**Comment by ShinokiRyosei** [comment]
OK
Good Job!

**Comment by ShinokiRyosei** [comment]
@yanack1225 できてなかったやん

**Comment by ShinokiRyosei** [comment]
`TableViewCellType1ViewController`から`SetPlaceTableViewCell`という名前にクラス名とファイル名を変更しておくこと

**Comment by yanack1225** [comment]
え？変えたよ？

**Comment by yanack1225** [comment]
え？

**Comment by yanack1225** [comment]
変えたのに戻ってる！？

**Comment by ShinokiRyosei** [comment]
`SetPlaceTableViewCellType1ViewController`って今なってるで

**Comment by yanack1225** [comment]
なんか直したはずのものが色々戻ってるんだけど。。。。今度、もっかい直す！

**Comment by ShinokiRyosei** [comment]
よろしく

**Comment by yanack1225** [comment]
他に直ってなかったissueあったらよろしく！

**Comment by ShinokiRyosei** [comment]
もちろん
できてなかったらきちんと差し戻すよ

**Comment by yanack1225** [comment]
変更完了！
